#!usr/bin/env/ python3


import scapy.all as sp 
import argparse


parser = argparse.ArgumentParser(description='search for other devices on the network')

parser.add_argument('-ip', help='ip/ip range of the device')

args = parser.parse_args()

IP = args.ip


def scan(ip):
	arp_req = sp.ARP(pdst=ip)
	brdcst = sp.Ether(dst='ff:ff:ff:ff:ff:ff')
	packet = brdcst / arp_req
	responded_list = sp.srp(packet, timeout = 1, verbose = False)[0]
	print('________________________________________________________')

	print('IP\t\tMAC Address')

	print('--------------------------------------------------------')

	for ele in responded_list:

		print(ele[1].psrc + "\t" + ele[1].hwsrc)

        
scan(IP)
